/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul
 */
public class Returnbooks extends javax.swing.JFrame {

    /**
     * Creates new form Returnbooks
     */
    public Returnbooks() {
        initComponents();
        Connect();
        
        stu_id();
    }
     Connection con;
     PreparedStatement pst;   
     ResultSet rs;
    
     
    public void Connect()  
   {
       
        try {
            Class.forName("oracle.jdbc.OracleDriver");
              String url="jdbc:oracle:thin:@//localhost:1521/XEPDB1";
               con=DriverManager.getConnection(url,"system","rahul123");
             
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Addbooks.class.getName()).log(Level.SEVERE, null, ex);
        }          
   }
          
     
        
    public void  stu_id()
    {
        try {
            pst=con.prepareStatement("select book_name  from issue");
            rs=pst.executeQuery();
           book_name.removeAllItems();
            while(rs.next())
            {
                book_name.addItem(rs.getString(1));
            }
        } catch (Exception e) {
           e.printStackTrace();
        }
        
    }
    
     
  
    public void load()
    {
        String splace=book_name.getSelectedItem().toString();
      
         
        
        try {
            pst=con.prepareStatement("SELECT  student_id,book_id ,book_category,book_author   from issue where book_name=?  ");
            pst.setString(1, splace);
        
            
            rs=pst.executeQuery();
            
            if(rs.next()==true)
            {
              
               stuid.setText(rs.getString(1));
               book_id.setText(rs.getString(2));
              book_category.setText(rs.getString(3));
              book_author.setText(rs.getString(4));
              
              
             
              
              
            }
      
            
            
        } catch (Exception e) {
           e.printStackTrace();
        }
    }
    
     
    public void  returnbook(){
        
       String stu_ids=book_name.getSelectedItem().toString();
          String choosebooks=stuid.getText();
        String stuname=book_id.getText();
          String bookcategory=book_category.getText();
           String bookauthor=book_author.getText();
             SimpleDateFormat date_form=new SimpleDateFormat("YYYY-MM-DD");
        String dates=date_form.format(duedate.getDate());
            
         
     

        
         
        try {
             pst= con.prepareStatement("insert into return values(?,?,?,?,?,?)");
            pst.setString(1,stu_ids);
            pst.setString(2,choosebooks);
            pst.setString(3,stuname);
            pst.setString(4,bookcategory);
            pst.setString(5, bookauthor);
            
            pst.setString(6,dates);
             
            
            int k= pst.executeUpdate();
            

                if(k==1){
                   
                                   
                           JOptionPane.showMessageDialog(this,"Book Return  Successfully");
                     
                }
                      
                    
                else
                {
                     JOptionPane.showMessageDialog(null,"Failed to Return Books");

                }
                
        }
        
          catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,"This Book Already Return");
             
        Logger.getLogger(Returnbooks.class.getName()).log(Level.SEVERE, null, ex);
          } 
        
        
    }
    
    
  
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        book_category = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        book_author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        returnbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        book_id = new javax.swing.JTextField();
        duedate = new com.toedter.calendar.JDateChooser();
        book_name = new javax.swing.JComboBox<>();
        stuid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Return your Book");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 301, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1170, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 90, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Book_Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Book_Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 20));

        book_category.setText(" ");
        getContentPane().add(book_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 320, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Book_Author");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, 30));

        book_author.setText(" ");
        getContentPane().add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 320, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Due Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 104, -1));

        returnbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnbtn.setText("Return");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 90, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 90, 40));
        getContentPane().add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 320, 40));
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 320, 40));

        book_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 320, 40));
        getContentPane().add(stuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 320, 40));

        setSize(new java.awt.Dimension(1180, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_searchActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        // TODO add your handling code here:
 
                
                returnbook();
           
        
        

    }//GEN-LAST:event_returnbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage r=new HomePage();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returnbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returnbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returnbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returnbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnbooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book_author;
    private javax.swing.JTextField book_category;
    private javax.swing.JTextField book_id;
    private javax.swing.JComboBox<String> book_name;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnbtn;
    private javax.swing.JButton search;
    private javax.swing.JTextField stuid;
    // End of variables declaration//GEN-END:variables
}
